<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup Label="Globals">
	  <SccProjectName>SAK</SccProjectName>
	  <SccProvider>SAK</SccProvider>
	  <SccAuxPath>SAK</SccAuxPath>
	  <SccLocalPath>SAK</SccLocalPath>
    <NoWarn>$(NoWarn);IDE0130;XA0101</NoWarn>
	</PropertyGroup>

	<PropertyGroup>
		<TargetFrameworks>net10.0-android;net10.0-ios;net10.0-maccatalyst;net10.0-windows10.0.19041.0</TargetFrameworks>
		<!-- <TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">$(TargetFrameworks);net8.0-windows10.0.19041.0</TargetFrameworks> -->
		<!-- Uncomment to also build the tizen app. You will need to install tizen by following this: https://github.com/Samsung/Tizen.NET -->
		<!-- <TargetFrameworks>$(TargetFrameworks);net8.0-tizen</TargetFrameworks> -->

		<!-- Note for MacCatalyst:
		The default runtime is maccatalyst-x64, except in Release config, in which case the default is maccatalyst-x64;maccatalyst-arm64.
		When specifying both architectures, use the plural <RuntimeIdentifiers> instead of the singular <RuntimeIdentifier>.
		The Mac App Store will NOT accept apps with ONLY maccatalyst-arm64 indicated;
		either BOTH runtimes must be indicated or ONLY macatalyst-x64. -->
		<!-- For example: <RuntimeIdentifiers>maccatalyst-x64;maccatalyst-arm64</RuntimeIdentifiers> -->

		<OutputType>Exe</OutputType>
		<RootNamespace>HardwareSampleMaui</RootNamespace>
		<UseMaui>true</UseMaui>
		<SingleProject>true</SingleProject>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<ApplicationTitle>HardwareSampleMaui</ApplicationTitle>
    <ProjectName>HardwareSampleMaui</ProjectName>
    <AssemblyName>HardwareSampleMaui</AssemblyName>
		<ApplicationId>com.companyname.hardwaresamplemaui</ApplicationId>
		<ApplicationDisplayVersion>2.0.0</ApplicationDisplayVersion>
		<ApplicationVersion>1</ApplicationVersion>

		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">15.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'maccatalyst'">15.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">21.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</SupportedOSPlatformVersion>
		<TargetPlatformMinVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</TargetPlatformMinVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'tizen'">6.5</SupportedOSPlatformVersion>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net10.0-android|AnyCPU'">
	  <PublishTrimmed>False</PublishTrimmed>
	  <RunAOTCompilation>False</RunAOTCompilation>
	  <DebugSymbols>True</DebugSymbols>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net10.0-ios|AnyCPU'">
	  <EnableSGenConc>True</EnableSGenConc>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net10.0-ios|AnyCPU'">
	  <EnableSGenConc>True</EnableSGenConc>
	</PropertyGroup>

	<PropertyGroup Condition="'$(TargetFramework)'=='net10.0-ios'">
	  <CodesignKey>Apple Development: Frank Haggar (G3ZX5TWSK2)</CodesignKey>
	  <CodesignProvision>VS: WildCard Development</CodesignProvision>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net10.0-android|AnyCPU'">
	  <TrimMode>copyused</TrimMode>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net10.0-maccatalyst|AnyCPU'">
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net10.0-maccatalyst|AnyCPU'">
    <RuntimeIdentifier>maccatalyst-x64</RuntimeIdentifier>
	</PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net10.0-windows10.0.19041.0|AnyCPU'">
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net10.0-windows10.0.19041.0|AnyCPU'">
	</PropertyGroup>

	<ItemGroup>
		<MauiIcon Include="Resources\AppIcon\appicon.svg" Color="#FFFFFF" />
		<MauiSplashScreen Include="Resources\Splash\splash.png" Color="#FFFFFF" BaseSize="300,69" />
		<MauiImage Include="Resources\Images\*" />
		<MauiFont Include="Resources\Fonts\*" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="DeviceFramework" Version="2.0.14" />
		<PackageReference Include="IDTechNeo.Maui" Version="2.0.3" />
		<PackageReference Include="IngenicoUpp" Version="2.0.3" />
		<PackageReference Include="Microsoft.Maui.Controls" Version="10.0.60" />
		<PackageReference Include="Microsoft.Maui.Controls.Compatibility" Version="10.0.60" />
		<PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="10.0.8" />
		<PackageReference Include="CommunityToolkit.Maui" Version="14.1.1" />
		<PackageReference Include="SlimCD" Version="3.4.4" />
		<PackageReference Include="SlimCDDevice" Version="5.0.3" />
		<PackageReference Include="SlimCDTypeLib" Version="2.1.2" />
	</ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net10.0-android'">
    <PackageReference Include="IDTech.Maui.Comm">
      <Version>3.2.5.439</Version>
    </PackageReference>
    <PackageReference Include="CommManagerAndroid">
      <Version>1.3.2</Version>
    </PackageReference>
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net10.0-ios'">
    <PackageReference Include="IDTech.Maui.Comm">
      <Version>3.2.5.439</Version>
    </PackageReference>
  </ItemGroup>

	<ItemGroup>
	  <Compile Update="Pages\DevicePage.xaml.cs">
	    <DependentUpon>DevicePage.xaml</DependentUpon>
	  </Compile>
	  <Compile Update="Pages\ConnectionPage.xaml.cs">
	    <DependentUpon>ConnectionPage.xaml</DependentUpon>
	  </Compile>
	  <Compile Update="Pages\TransactionPage.xaml.cs">
	    <DependentUpon>TransactionPage.xaml</DependentUpon>
	  </Compile>
	</ItemGroup>

	<ItemGroup>
	  <Content Update="C:\Users\Dennis\.nuget\packages\ingenicoupp\2.0.1\contentFiles\any\net10.0\IngenicoUpp.ini">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content>
	</ItemGroup>

	<ItemGroup>
	  <MauiXaml Update="Pages\ConnectionPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Pages\TransactionPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	</ItemGroup>

	</Project>
